[package]
name = "pbf_font_tools"
version = "2.0.0"
authors = ["Ian Wagner <ian@stadiamaps.com>", "Luke Seelenbinder <luke@stadiamaps.com>"]
license = "BSD-3-Clause"
repository = "https://github.com/stadiamaps/pbf_font_tools"
readme = "README.md"
description = "Tools for working with SDF font glyphs encoded in protobuf format."
keywords = ["sdf", "protobuf", "fonts"]
categories = ["encoding", "parsing", "rendering::data-formats"]
edition = "2021"

[features]
freetype = ["freetype-rs", "sdf_glyph_renderer/freetype"]

[dependencies]
futures = "0.3.14"
protobuf = "2.22.1"

[dependencies.tokio]
version = "1.12.0"

[build-dependencies]
glob = "0.3.0"
protobuf-codegen-pure = "2.22.1"

[dev-dependencies.tokio]
version = "1.12.0"
features = ["fs", "io-util", "macros", "rt"]

[dependencies.freetype-rs]
version = "0.28.0"
optional = true

[dependencies.sdf_glyph_renderer]
version = "0.1.3"
optional = true
